@startuml dungeon_crawler

class Juego {
    -nivelActual
    -jugador
    -puntuacion
    +iniciarJuego()
    +actualizarNivel()
    +incrementarPuntuacion()
    +mostrarPantallaFinal()
}

class Nivel {
    -dificultad
    -numeroMazmorras
    +aumentarDificultad()
    +generarMazmorra()
}

class Jugador {
    -nombre
    -vida
    -dañoBase
    -posicion
    +mover()
    +atacar()
    +curar()
    +morir()
}


class Habitacion {
    -tipo
    -posicion
    +inicializar()
    +mostrar()
    +generarEnemigos()
}

class Enemigo {
    -tipo
    -vida
    -dañoBase
    -posicion
    +mover()
    +atacar()
    +morir()
}

class Arma{
    +multiplicacion de daño()
}
class Armadura{
    +multiplicacion de reduccion de daño()
}
class Tesoro{
    +generarArma()
    +generarArmadura()
}
class Calidad
class Daño{
    +calculoDeDaño()
}
class normal{
    -posibilidadDeSalir
}
class raro{
    -posibilidadDeSalir
}
class epico{
    -posibilidadDeSalir
}
class legendario{
    -posibilidadDeSalir
}


Juego "1" *-- "*" Nivel
Juego "1" *-- "1" Jugador

Nivel "1" *-- "*" Habitacion

Habitacion "1" *-- "*" Enemigo

Jugador "1" o-- "*" Arma
Jugador "1" o-- "*" Armadura
Jugador "1" o-- "*" Tesoro
Jugador "1" *-- "1" Daño

Enemigo "1" o-- "1" Arma
Enemigo "1" o-- "1" Armadura
Enemigo "1" *-- "1" Tesoro
Enemigo "1" *-- "1" Daño

Arma "1" o-- "1" Calidad
Armadura "1" o-- "1" Calidad

normal --|> Calidad
raro --|> Calidad
epico --|> Calidad
legendario --|> Calidad
@enduml